/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemgestiunepub;

import java.awt.Color;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.SwingUtilities;
import static javax.swing.SwingUtilities.convertPoint;

/**
 *
 * @author User
 */
public class FereastraMeseAdministrator extends javax.swing.JFrame
                                implements MouseListener, MouseMotionListener {

    /**
     * Creates new form FereastraMeseAdministrator
     */
    private int laturaMasa;
    private Point pozitieStart;
    private JButton masaSelectata;
    private static ArrayList<JButton> listaMese;
    Boolean modStergere;

    public FereastraMeseAdministrator() {
        initComponents();
        
        // Initializare variabile
        laturaMasa = 75;
        listaMese = new ArrayList();
        modStergere = false;
        
        // Extragere mese din BD
        try{
            Connection con = BazaDeDate.getInstanta();
            Statement stmt = con.createStatement();
            String sql = "SELECT * FROM Masa";
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()) {
                // Extragere pozitie masa
                int x = rs.getInt(2);
                int y = rs.getInt(3);
                
                // Instantiere masa
                JButton tmp = new JButton();
                tmp.setLocation(x, y);
                tmp.setSize(laturaMasa, laturaMasa);
                tmp.addMouseListener(this);
                tmp.addMouseMotionListener(this);

                // Adaugare masa in fereastra
                tmp.setVisible(true);
                jPanel1.add(tmp);
                // Adaugare masa in memorie
                listaMese.add(tmp);
            }
            rs.close();
            stmt.close();
            
            // Actualizare fereastra
            this.revalidate();
            this.repaint();
        }
        catch(Exception e){
            System.out.println("EROARE EXTRAGERE MESE DIN BD");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butonAdaugareMasa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        butonModStergere = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butonAdaugareMasa.setText("adauga masa");
        butonAdaugareMasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonAdaugareMasaActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        butonModStergere.setText("mod stergere");
        butonModStergere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonModStergereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butonAdaugareMasa)
                    .addComponent(butonModStergere))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(butonAdaugareMasa)
                        .addGap(18, 18, 18)
                        .addComponent(butonModStergere))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonAdaugareMasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonAdaugareMasaActionPerformed
        // TODO add your handling code here:
        int xImplicit = 100;
        int yImplicit = 100;
        
        JButton tmp = new JButton();
        tmp.setText("");
        tmp.setLocation(xImplicit, yImplicit);
        tmp.setSize(laturaMasa, laturaMasa);

        // Verificare sa nu se poata instantia o masa noua
        // Daca in pozitia de spawn se afla alta masa
        for(int i=0; i<listaMese.size(); i++)
            if(tmp.getBounds().intersects(listaMese.get(i).getBounds())){
                System.out.println("Exista alta masa in pozitia de spawn.");
                return;
            }
        
        try {
            Connection con = BazaDeDate.getInstanta();
            String sql = "INSERT INTO Masa(x, y) value (?, ?)";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setInt(1, xImplicit);
            stmt.setInt(2, yImplicit);
            stmt.execute();
            stmt.close();
            System.out.println("Masa adaugata cu succes.");
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("EROARE BUTON ADAUGA MASA");
        }
        
        listaMese.add(tmp);
        jPanel1.add(tmp);
        tmp.setVisible(true);
        
        tmp.addMouseListener(this);
        tmp.addMouseMotionListener(this);

        // Recalculeaza pozitii Layout Manager
        this.revalidate();
        // Redeseneaza fereastra
        this.repaint();
    }//GEN-LAST:event_butonAdaugareMasaActionPerformed

    private void butonModStergereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonModStergereActionPerformed
        // TODO add your handling code here:
        if (modStergere == false) {
            butonModStergere.setBackground(Color.RED);
            modStergere = true;
        } else {
            modStergere = false;
            butonModStergere.setBackground(butonAdaugareMasa.getBackground());
        }
    }//GEN-LAST:event_butonModStergereActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FereastraMeseAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FereastraMeseAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FereastraMeseAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FereastraMeseAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FereastraMeseAdministrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonAdaugareMasa;
    private javax.swing.JButton butonModStergere;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
    }

    @Override
    public void mousePressed(MouseEvent e) {
        // Detectarea mesei apasate
        masaSelectata = (JButton) e.getSource();
        
        if (modStergere == true) {
            // Stergerea mesei din baza de date
            try {
                Connection con = BazaDeDate.getInstanta();
                String sql = "DELETE FROM Masa WHERE x = ? AND y = ?";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setInt(1, masaSelectata.getX());
                ps.setInt(2, masaSelectata.getY());
                ps.execute();
                ps.close();
            } catch (ClassNotFoundException | SQLException ex) {
                System.out.println("EROARE STERGERE MASA");
            }
            
            //Stergerea mesei din lista
            listaMese.remove(masaSelectata);
            
            // Stergerea mesei din fereastra
            jPanel1.remove(masaSelectata);
            jPanel1.revalidate();
            jPanel1.repaint();
            return;
        }
        
        pozitieStart = SwingUtilities.convertPoint(masaSelectata, e.getPoint(),
                                                    masaSelectata.getParent());
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        pozitieStart = null;
        masaSelectata = null;
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }

    @Override
    public void mouseDragged(MouseEvent e) {
        Point pozitieMouse = convertPoint(masaSelectata, e.getPoint(),
                                            masaSelectata.getParent());
        if (this.getBounds().contains(pozitieMouse)) {
            Point pozitieVeche = masaSelectata.getLocation();
            Point pozitieNoua = masaSelectata.getLocation();
            pozitieNoua.translate(pozitieMouse.x - pozitieStart.x,
                                    pozitieMouse.y - pozitieStart.y);

            // Prevenim depasirea panoului
            pozitieNoua.x = Math.max(pozitieNoua.x, 0);
            pozitieNoua.y = Math.max(pozitieNoua.y, 0);
            pozitieNoua.x = Math.min(pozitieNoua.x, masaSelectata.getParent().getWidth()
                                        - masaSelectata.getWidth());
            pozitieNoua.y = Math.min(pozitieNoua.y, masaSelectata.getParent().getHeight()
                                        - masaSelectata.getHeight());

            // Prevenim coliziunea
            for (int i = 0; i < listaMese.size(); i++) {
                Rectangle masaInViitor = new Rectangle(pozitieNoua.x, pozitieNoua.y,
                                                        laturaMasa, laturaMasa);
                
                if (masaInViitor.intersects(listaMese.get(i).getBounds())
                        & (listaMese.get(i) != masaSelectata) ) {
                    return;
                }
            }

            // Actualizare locatie
            pozitieStart = pozitieMouse;
            masaSelectata.setLocation(pozitieNoua);
            
            // Actualizare locatie in BD
            try {
                Connection con = BazaDeDate.getInstanta();
                String sql = "UPDATE Masa SET x = ?, y = ? WHERE x = ? AND y = ?";
                PreparedStatement stmt = con.prepareStatement(sql);
                stmt.setInt(1, pozitieNoua.x);
                stmt.setInt(2, pozitieNoua.y);
                stmt.setInt(3, pozitieVeche.x);
                stmt.setInt(4, pozitieVeche.y);
                stmt.execute();
                stmt.close();
            } catch (ClassNotFoundException | SQLException ex) {
                System.out.println("EROARE ACTUALIZARE LOCATIE MASA IN BD");
            }
        }
    }

    @Override
    public void mouseMoved(MouseEvent e) {
    }
}
