/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemgestiunepub;

import java.awt.Color;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import static javax.swing.SwingUtilities.convertPoint;

/**
 *
 * @author User
 */
public class FereastraMeseAdmin extends javax.swing.JFrame
        implements MouseListener, MouseMotionListener {

    /**
     * Creates new form FereastraMeseAdmin
     */
    private Point pozitieStart;
    private JButton masaSelectata;
    private Boolean modStergere;

    public FereastraMeseAdmin() {
        initComponents();

        // Initializare variabile
        modStergere = false;
        jLabelIdUser.setText(String.valueOf(FereastraLogin.idUser));

        ModelMasa.citesteDinBd(panouMese, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butonAdaugareMasa = new javax.swing.JButton();
        panouMese = new javax.swing.JPanel();
        butonModStergere = new javax.swing.JButton();
        butonGestionareAngajati = new javax.swing.JButton();
        butonGestionareProduse = new javax.swing.JButton();
        jLabelIdUser = new javax.swing.JLabel();
        butonRaport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butonAdaugareMasa.setText("adauga masa");
        butonAdaugareMasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonAdaugareMasaActionPerformed(evt);
            }
        });

        panouMese.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout panouMeseLayout = new javax.swing.GroupLayout(panouMese);
        panouMese.setLayout(panouMeseLayout);
        panouMeseLayout.setHorizontalGroup(
            panouMeseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        panouMeseLayout.setVerticalGroup(
            panouMeseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        butonModStergere.setText("mod stergere");
        butonModStergere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonModStergereActionPerformed(evt);
            }
        });

        butonGestionareAngajati.setText("gestioneaza angajati");
        butonGestionareAngajati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonGestionareAngajatiActionPerformed(evt);
            }
        });

        butonGestionareProduse.setText("gestioneaza produse");
        butonGestionareProduse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonGestionareProduseActionPerformed(evt);
            }
        });

        jLabelIdUser.setText("jLabel1");

        butonRaport.setText("genereaza raport");
        butonRaport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonRaportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panouMese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIdUser)
                    .addComponent(butonModStergere)
                    .addComponent(butonAdaugareMasa)
                    .addComponent(butonGestionareAngajati)
                    .addComponent(butonGestionareProduse)
                    .addComponent(butonRaport))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panouMese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelIdUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butonAdaugareMasa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butonModStergere)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butonGestionareAngajati)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butonGestionareProduse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butonRaport)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butonAdaugareMasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonAdaugareMasaActionPerformed
        // TODO add your handling code here:
        int xImplicit = 100;
        int yImplicit = 100;

        // Creare masa
        ModelMasa masa = new ModelMasa(xImplicit, yImplicit);

        if (ModelMasa.seSuprapune(masa.buton)) {
            JOptionPane.showMessageDialog(new JFrame(), "Exista alta masa in pozitia de spawn.");
            return;
        }

        ControllerMasa.adauga(masa, this, panouMese);
    }//GEN-LAST:event_butonAdaugareMasaActionPerformed

    private void butonModStergereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonModStergereActionPerformed
        // TODO add your handling code here:
        if (modStergere == false) {
            butonModStergere.setBackground(Color.RED);
            modStergere = true;
        } else {
            modStergere = false;
            butonModStergere.setBackground(butonAdaugareMasa.getBackground());
        }
    }//GEN-LAST:event_butonModStergereActionPerformed

    private void butonGestionareAngajatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonGestionareAngajatiActionPerformed
        // TODO add your handling code here:
        FereastraUseri f = new FereastraUseri();
        f.setAlwaysOnTop(true);
        f.setVisible(true);
        f.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_butonGestionareAngajatiActionPerformed

    private void butonGestionareProduseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonGestionareProduseActionPerformed
        // TODO add your handling code here:
        FereastraProduse f = new FereastraProduse();
        f.setAlwaysOnTop(true);
        f.setVisible(true);
        f.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_butonGestionareProduseActionPerformed

    private void butonRaportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonRaportActionPerformed
        // TODO add your handling code here:
        FereastraRaport f = new FereastraRaport();
        f.setAlwaysOnTop(true);
        f.setVisible(true);
        f.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_butonRaportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FereastraMeseAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FereastraMeseAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FereastraMeseAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FereastraMeseAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FereastraMeseAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonAdaugareMasa;
    private javax.swing.JButton butonGestionareAngajati;
    private javax.swing.JButton butonGestionareProduse;
    private javax.swing.JButton butonModStergere;
    private javax.swing.JButton butonRaport;
    private javax.swing.JLabel jLabelIdUser;
    private javax.swing.JPanel panouMese;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
    }

    @Override
    public void mousePressed(MouseEvent e) {
        // Detectarea mesei apasate
        masaSelectata = (JButton) e.getSource();
        
        if (modStergere == true) {
            ControllerMasa.sterge(masaSelectata, panouMese);
            return;
        }
        
        pozitieStart = SwingUtilities.convertPoint(masaSelectata, e.getPoint(),
                masaSelectata.getParent());
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        pozitieStart = null;
        masaSelectata = null;
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }

    @Override
    public void mouseDragged(MouseEvent e) {
        Point pozitieMouse = convertPoint(masaSelectata, e.getPoint(),
                masaSelectata.getParent());

        if (!(panouMese.getBounds().contains(pozitieMouse))) {
            return;
        }
        
        Point pozitieVeche = masaSelectata.getLocation();
        Point pozitieNoua = masaSelectata.getLocation();
        pozitieNoua.translate(pozitieMouse.x - pozitieStart.x, pozitieMouse.y - pozitieStart.y);

        // Prevenim depasirea panoului
        pozitieNoua.x = Math.max(pozitieNoua.x, 0);
        pozitieNoua.y = Math.max(pozitieNoua.y, 0);
        pozitieNoua.x = Math.min(pozitieNoua.x, masaSelectata.getParent().getWidth()
                - masaSelectata.getWidth());
        pozitieNoua.y = Math.min(pozitieNoua.y, masaSelectata.getParent().getHeight()
                - masaSelectata.getHeight());

        // Prevenim coliziunea
        for (int i = 0; i < ModelMasa.mese.size(); i++) {
            Rectangle masaInViitor = new Rectangle(pozitieNoua.x, pozitieNoua.y,
                    ModelMasa.latura, ModelMasa.latura);

            if (masaInViitor.intersects(ModelMasa.mese.get(i).buton.getBounds())
                    & (ModelMasa.mese.get(i).buton != masaSelectata)) {
                return;
            }
        }

        // Actualizare locatie
        pozitieStart = pozitieMouse;
        masaSelectata.setLocation(pozitieNoua);
        ModelMasa.actualizeazaPozitieInBd(pozitieNoua, pozitieVeche);

        panouMese.revalidate();
        panouMese.repaint();
    }

    @Override
    public void mouseMoved(MouseEvent e) {
    }
}
