/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemgestiunepub;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FereastraProduse extends javax.swing.JFrame {

    /**
     * Creates new form GestionareProduse
     */
    public FereastraProduse() {
        initComponents();
        Produs.citeste();
        Produs.completeazaJtable((DefaultTableModel) jTable1.getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        campNume = new javax.swing.JTextField();
        campPret = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        butonAdaugareProdus = new javax.swing.JButton();
        butonStergereProdus = new javax.swing.JButton();
        butonModificareProdus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nume", "pret"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("nume");

        jLabel2.setText("pret");

        butonAdaugareProdus.setText("adauga");
        butonAdaugareProdus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonAdaugareProdusActionPerformed(evt);
            }
        });

        butonStergereProdus.setText("sterge");
        butonStergereProdus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonStergereProdusActionPerformed(evt);
            }
        });

        butonModificareProdus.setText("modifica");
        butonModificareProdus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonModificareProdusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butonModificareProdus)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(butonStergereProdus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(butonAdaugareProdus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campPret)
                            .addComponent(campNume))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campPret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(butonAdaugareProdus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butonStergereProdus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butonModificareProdus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonAdaugareProdusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonAdaugareProdusActionPerformed
        // TODO add your handling code here:
        String nume = campNume.getText();
        String pret = campPret.getText();
        // Adaugare in BD
        BazaDeDate.adaugaProdus(nume, pret);
        int id = BazaDeDate.returneazaUltimaCheie();
        Produs produs = new Produs(id, nume, Integer.parseInt(pret));
        // Adaugare in lista statica
        Produs.adauga(produs);
        // Adaugare in JTable
        Produs.adaugaJtable((DefaultTableModel) jTable1.getModel(), produs);
    }//GEN-LAST:event_butonAdaugareProdusActionPerformed

    private void butonStergereProdusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonStergereProdusActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRowCount() != 1) {
            return;
        }
        // Identificare produs
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int indexRand = jTable1.getSelectedRow();
        String id = (String) model.getValueAt(indexRand, 0);
        // Stergere din BD
        BazaDeDate.stergeProdus(id);
        // Stergere din JTable
        model.removeRow(indexRand);
    }//GEN-LAST:event_butonStergereProdusActionPerformed

    private void butonModificareProdusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonModificareProdusActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedColumnCount() != 1) {
            return;
        }
        // Extragere date noi din text field
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int indexRand = jTable1.getSelectedRow();
        String stringId = (String) model.getValueAt(indexRand, 0);
        String nume = campNume.getText();
        String stringPret = campPret.getText();
        //Actualizeaza in BD
        BazaDeDate.actualizeazaProdus(stringId, nume, stringPret);
        // Actualizare in jTable
        model.setValueAt(nume, indexRand, 1);
        model.setValueAt(stringPret, indexRand, 2);
        model.fireTableDataChanged();
        //Actualizeaza in lista statica
        int index = Produs.getIndex(Integer.parseInt(stringId));
        Produs produs = Produs.get(index);
        produs.setNume(nume);
        produs.setPret(Integer.parseInt(stringPret));
    }//GEN-LAST:event_butonModificareProdusActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        String nume = (String) model.getValueAt(row, 1);
        String pret = (String) model.getValueAt(row, 2);
        campNume.setText(nume);
        campPret.setText(pret);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FereastraProduse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FereastraProduse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FereastraProduse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FereastraProduse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FereastraProduse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonAdaugareProdus;
    private javax.swing.JButton butonModificareProdus;
    private javax.swing.JButton butonStergereProdus;
    private javax.swing.JTextField campNume;
    private javax.swing.JTextField campPret;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
